### PR TITLE
Optimizations for network

### PR DESCRIPTION
**Pull request by tsao-chi**
port https://github.com/Akarin-project/StarLink/commit/afcf65b9c39b32fd6291a6dd6769d2c28c5c0173 https://github.com/Akarin-project/StarLink/commit/f0312e134ef4910ae6bc7d45926769c333f46461 https://github.com/Akarin-project/StarLink/commit/712412f220380a1a452aa4a4d3da970c9c9c8417
@cakoyo please review this commit

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
Doesn't compile yet

**Comment by tsao-chi** [comment]
@LegacyGamerHD So it's WIP

**Comment by cakoyo** [comment]
This is a big patch that cost much to maintain imo with relatively minor benefits and still have a few points to be optimized, so I don't really think it's a necessity for this port

**Comment by josephworks** [comment]
I have to agree with @cakoyo for this one. If you think this is still worth it, then reopen the PR or comment.

**Comment by tsao-chi** [comment]
@cakoyo But it's fine to add it as long as it doesn't break anything. It can be easily revert once it breaks.

**Comment by josephworks** [comment]
Good point

**Pull request merged**
