### PR TITLE
Auto publish releases with GitHub Actions

### PR DESCRIPTION
**Pull request by MerdedSpade**

### CODE REVIEW

**Comment by josephworks** [comment]
Not every build is a release...

**Comment by MerdedSpade** [comment]
I mean another, just release for every commit

**Comment by josephworks** [comment]
Not every commit is a release...

**Comment by MerdedSpade** [comment]
Like build, but release

**Comment by josephworks** [comment]
We do releases manually as it is better to do so.

**Comment by MerdedSpade** [comment]
I made draft release

**Comment by tsao-chi** [comment]
Users can download binaries from https://github.com/Akarin-project/Akarin/actions?query=event%3Apush+branch%3A1.15.2

**Comment by tsao-chi** [comment]
Why it's not end yet? https://github.com/Akarin-project/Akarin/pull/143/checks?check_run_id=554293215

**Comment by tsao-chi** [comment]
Why is it not finish yet? https://github.com/Akarin-project/Akarin/pull/143/checks?check_run_id=554293215

**Comment by MerdedSpade** [comment]
@tsao-chi 
Can you open upload artifacts logs? 
When i clicking nothing happening

**Comment by LegacyGamerHD** [comment]
it seems stuck on uplauding the jar

**Comment by cakoyo** [comment]
It would be fine if it is prefix-based such as [RELEASE] or [TAG], or imo it can be tag instead of release, not sure whether it is possible.

**Comment by MerdedSpade** [comment]
Hmm. Tag is big very big lol. We can just replace release name with tag.

**Comment by LegacyGamerHD** [comment]
we can close this

**Pull request closed without merging**
