### PR TITLE
More fixes and optimisations

### PR DESCRIPTION
**Pull request by FatSaw**

### CODE REVIEW

**Comment by josephworks** [comment]
Why is this closed and not merged?

**Comment by FatSaw** [comment]
> Why is this closed and not merged?

Some checks took too long.  During this time, I decided to double-check some changes.

**Comment by josephworks** [comment]
Let me know when this is ready for my review.

**Comment by FatSaw** [comment]
It's ready for review. But Iam not sure that Explosions calculation is accuracly. Maybe we need add some configs to enable/disable some changes.

**Review by josephworks — APPROVED** [review]
LGTM

**Comment by josephworks** [comment]
@FatSaw I accidentally merged. Please do add configs (maybe a new akarin.yml).

**Pull request merged**
