### PR TITLE
Upstream mixin experimental

### PR DESCRIPTION
**Pull request by FatSaw**

### CODE REVIEW

**Comment by HowardZHY** [comment]
Why did you include the mixin lib source in src/main?

**Comment by josephworks** [comment]
Yes, @FatSaw please let me know if you want me to fork a repo where we can apply our changes.

**Comment by FatSaw** [comment]
> Why did you include the mixin lib source in src/main?

Because Mixin 8.+ did not want to work with Legacylauncher otherwise, or I am doing something wrong. I asked in the Sponge discord how to work with Legacylauncher at 8 Mixin. They answered me that Mixin himself should detect Legacylauncher, but this does not happen (Mixin first tries to find Modlauncher, does not find it and crashing).
Mixin that I included in the source does not contain a start for Modlauncher and starts perfectly with Legacylauncher.

**Comment by josephworks** [comment]
Ok, so could we move your changes to Mixin to a new repository?

**Comment by FatSaw** [comment]
> Ok, so could we move your changes to Mixin to a new repository?

Yes, it would be better than leaving the mixin sources here.

**Comment by josephworks** [comment]
@FatSaw Please move the org.spongepowered.mixin here: https://github.com/Akarin-project/Mixin and let me know when you are finished! I will deploy it to the CI and Repo.

**Comment by FatSaw** [comment]
> @FatSaw Please move the org.spongepowered.mixin here: https://github.com/Akarin-project/Mixin and let me know when you are finished! I will deploy it to the CI and Repo.

I finished.

**Comment by josephworks** [comment]
image

**Comment by josephworks** [comment]
Please remove the mixin from akarin source and add that entry to the pom.xml

**Comment by FatSaw** [comment]
LegacyLauncher mixin dependency need to be upgraded to avoid conflicts.
I close this pull reqest and make new pull reqest later after tests.

**Pull request closed without merging**
