### PR TITLE
Modifiy EnderChest Size

### PR DESCRIPTION
**Pull request by DoctaEnkoda**
Hello I suggest a good suggestion (i try local) for change size enderchest, vanilla always 27 but with plugin, we can update to 54 ! After it's possible add all line Enderchest ! I can send my code if you want :)

Possible too for Starlink

### CODE REVIEW

**Comment by DoctaEnkoda** [comment]
BlockEnderChest.java => https://pastebin.com/2h0s0fBS
ContainerChest => https://pastebin.com/u48WjiTn

**Comment by cakoyo** [comment]
Definitely an interesting idea, but it's also highly possible to break or having inconsistent behavior with plugins. I think one better solution is to provide an API to do with this, or simply a configuration cause you know no everyone wants this though it's cool.

**Comment by DoctaEnkoda** [comment]
So add config in Akarin.yml is better for change value if you want or not ?

**Comment by cakoyo** [comment]
@DoctaEnkoda I think so if you sure that simply editing that value can properly do it.

**Comment by LegacyGamerHD** [comment]
i woeld love to see them bigger

**Pull request closed without merging**
