### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by tsao-chi**

### CODE REVIEW

**Comment by josephworks** [comment]
We have Jenkins, and I just set It up with discord today. I will setup Auto-build tomorrow.

**Comment by MerdedSpade** [comment]
But GitHub Actions can publish releases

**Comment by tsao-chi** [comment]
It's necessary for PR

**Comment by josephworks** [comment]
@MerdedSpade Jenkins can also publish releases, but that is not necessary right now.

@tsao-chi wdym?

**Comment by tsao-chi** [comment]
@josephworks
It's necessary for Pull requests.

**Comment by josephworks** [comment]
Accidentally closed, I reopened.
Janine can build PRs

**Comment by MerdedSpade** [comment]
Hm. GitHub Actions like Jenkins, but fast.
I don't like Jenkins because it has 300kb/s downloads.

**Comment by josephworks** [comment]
@MerdedSpade , my Jenkins has 60mb download not 300kb..

**Comment by josephworks** [comment]
What I'll do is merge pull request for now, and set up Jenkins later.

**Pull request merged**
